(generic_command
  command: (command_name) @conceal
  (#any-of? @conceal "\\emph" "\\mathit" "\\textit" "\\mathbf" "\\textbf" "\\mathrm" "\\textsc")
  (#set! conceal ""))

((generic_command
   command: (command_name)
   arg: (curly_group)) @text.math
 (#any-of? @text.math 
  "\\mathbb{A}" "\\mathbb{B}" "\\mathbb{C}" "\\mathbb{D}" "\\mathbb{E}" 
  "\\mathbb{F}" "\\mathbb{G}" "\\mathbb{H}" "\\mathbb{I}" "\\mathbb{J}" 
  "\\mathbb{K}" "\\mathbb{L}" "\\mathbb{M}" "\\mathbb{N}" "\\mathbb{O}" 
  "\\mathbb{P}" "\\mathbb{Q}" "\\mathbb{R}" "\\mathbb{S}" "\\mathbb{T}" 
  "\\mathbb{U}" "\\mathbb{V}" "\\mathbb{W}" "\\mathbb{X}" "\\mathbb{Y}" 
  "\\mathbb{Z}" "\\mathsf{a}" "\\mathsf{b}" "\\mathsf{c}" "\\mathsf{d}" 
  "\\mathsf{e}" "\\mathsf{f}" "\\mathsf{g}" "\\mathsf{h}" "\\mathsf{i}" 
  "\\mathsf{j}" "\\mathsf{k}" "\\mathsf{l}" "\\mathsf{m}" "\\mathsf{n}" 
  "\\mathsf{o}" "\\mathsf{p}" "\\mathsf{q}" "\\mathsf{r}" "\\mathsf{s}" 
  "\\mathsf{t}" "\\mathsf{u}" "\\mathsf{v}" "\\mathsf{w}" "\\mathsf{x}" 
  "\\mathsf{y}" "\\mathsf{z}" "\\mathsf{A}" "\\mathsf{B}" "\\mathsf{C}" 
  "\\mathsf{D}" "\\mathsf{E}" "\\mathsf{F}" "\\mathsf{G}" "\\mathsf{H}" 
  "\\mathsf{I}" "\\mathsf{J}" "\\mathsf{K}" "\\mathsf{L}" "\\mathsf{M}" 
  "\\mathsf{N}" "\\mathsf{O}" "\\mathsf{P}" "\\mathsf{Q}" "\\mathsf{R}" 
  "\\mathsf{S}" "\\mathsf{T}" "\\mathsf{U}" "\\mathsf{V}" "\\mathsf{W}" 
  "\\mathsf{X}" "\\mathsf{Y}" "\\mathsf{Z}" "\\mathfrak{a}" "\\mathfrak{b}" 
  "\\mathfrak{c}" "\\mathfrak{d}" "\\mathfrak{e}" "\\mathfrak{f}" "\\mathfrak{g}" 
  "\\mathfrak{h}" "\\mathfrak{i}" "\\mathfrak{j}" "\\mathfrak{k}" "\\mathfrak{l}" 
  "\\mathfrak{m}" "\\mathfrak{n}" "\\mathfrak{o}" "\\mathfrak{p}" "\\mathfrak{q}" 
  "\\mathfrak{r}" "\\mathfrak{s}" "\\mathfrak{t}" "\\mathfrak{u}" "\\mathfrak{v}" 
  "\\mathfrak{w}" "\\mathfrak{x}" "\\mathfrak{y}" "\\mathfrak{z}" "\\mathfrak{A}" 
  "\\mathfrak{B}" "\\mathfrak{C}" "\\mathfrak{D}" "\\mathfrak{E}" "\\mathfrak{F}" 
  "\\mathfrak{G}" "\\mathfrak{H}" "\\mathfrak{I}" "\\mathfrak{J}" "\\mathfrak{K}" 
  "\\mathfrak{L}" "\\mathfrak{M}" "\\mathfrak{N}" "\\mathfrak{O}" "\\mathfrak{P}" 
  "\\mathfrak{Q}" "\\mathfrak{R}" "\\mathfrak{S}" "\\mathfrak{T}" "\\mathfrak{U}" 
  "\\mathfrak{V}" "\\mathfrak{W}" "\\mathfrak{X}" "\\mathfrak{Y}" "\\mathfrak{Z}" 
  "\\mathscr{A}" "\\mathscr{B}" "\\mathscr{C}" "\\mathscr{D}" "\\mathscr{E}" 
  "\\mathscr{F}" "\\mathscr{G}" "\\mathscr{H}" "\\mathscr{I}" "\\mathscr{J}" 
  "\\mathscr{K}" "\\mathscr{L}" "\\mathscr{M}" "\\mathscr{N}" "\\mathscr{O}" 
  "\\mathscr{P}" "\\mathscr{Q}" "\\mathscr{R}" "\\mathscr{S}" "\\mathscr{T}" 
  "\\mathscr{U}" "\\mathscr{V}" "\\mathscr{W}" "\\mathscr{X}" "\\mathscr{Y}" 
  "\\mathscr{Z}" "\\mathcal{A}" "\\mathcal{B}" "\\mathcal{C}" "\\mathcal{D}" 
  "\\mathcal{E}" "\\mathcal{F}" "\\mathcal{G}" "\\mathcal{H}" "\\mathcal{I}" 
  "\\mathcal{J}" "\\mathcal{K}" "\\mathcal{L}" "\\mathcal{M}" "\\mathcal{N}" 
  "\\mathcal{O}" "\\mathcal{P}" "\\mathcal{Q}" "\\mathcal{R}" "\\mathcal{S}" 
  "\\mathcal{T}" "\\mathcal{U}" "\\mathcal{V}" "\\mathcal{W}" "\\mathcal{X}" 
  "\\mathcal{Y}" "\\mathcal{Z}" "\\symbb{A}" "\\symbb{B}" "\\symbb{C}" "\\symbb{D}" "\\symbb{E}" 
  "\\symbb{F}" "\\symbb{G}" "\\symbb{H}" "\\symbb{I}" "\\symbb{J}" 
  "\\symbb{K}" "\\symbb{L}" "\\symbb{M}" "\\symbb{N}" "\\symbb{O}" 
  "\\symbb{P}" "\\symbb{Q}" "\\symbb{R}" "\\symbb{S}" "\\symbb{T}" 
  "\\symbb{U}" "\\symbb{V}" "\\symbb{W}" "\\symbb{X}" "\\symbb{Y}" 
  "\\symbb{Z}" "\\symsf{a}" "\\symsf{b}" "\\symsf{c}" "\\symsf{d}" 
  "\\symsf{e}" "\\symsf{f}" "\\symsf{g}" "\\symsf{h}" "\\symsf{i}" 
  "\\symsf{j}" "\\symsf{k}" "\\symsf{l}" "\\symsf{m}" "\\symsf{n}" 
  "\\symsf{o}" "\\symsf{p}" "\\symsf{q}" "\\symsf{r}" "\\symsf{s}" 
  "\\symsf{t}" "\\symsf{u}" "\\symsf{v}" "\\symsf{w}" "\\symsf{x}" 
  "\\symsf{y}" "\\symsf{z}" "\\symsf{A}" "\\symsf{B}" "\\symsf{C}" 
  "\\symsf{D}" "\\symsf{E}" "\\symsf{F}" "\\symsf{G}" "\\symsf{H}" 
  "\\symsf{I}" "\\symsf{J}" "\\symsf{K}" "\\symsf{L}" "\\symsf{M}" 
  "\\symsf{N}" "\\symsf{O}" "\\symsf{P}" "\\symsf{Q}" "\\symsf{R}" 
  "\\symsf{S}" "\\symsf{T}" "\\symsf{U}" "\\symsf{V}" "\\symsf{W}" 
  "\\symsf{X}" "\\symsf{Y}" "\\symsf{Z}" "\\symfrak{a}" "\\symfrak{b}" 
  "\\symfrak{c}" "\\symfrak{d}" "\\symfrak{e}" "\\symfrak{f}" "\\symfrak{g}" 
  "\\symfrak{h}" "\\symfrak{i}" "\\symfrak{j}" "\\symfrak{k}" "\\symfrak{l}" 
  "\\symfrak{m}" "\\symfrak{n}" "\\symfrak{o}" "\\symfrak{p}" "\\symfrak{q}" 
  "\\symfrak{r}" "\\symfrak{s}" "\\symfrak{t}" "\\symfrak{u}" "\\symfrak{v}" 
  "\\symfrak{w}" "\\symfrak{x}" "\\symfrak{y}" "\\symfrak{z}" "\\symfrak{A}" 
  "\\symfrak{B}" "\\symfrak{C}" "\\symfrak{D}" "\\symfrak{E}" "\\symfrak{F}" 
  "\\symfrak{G}" "\\symfrak{H}" "\\symfrak{I}" "\\symfrak{J}" "\\symfrak{K}" 
  "\\symfrak{L}" "\\symfrak{M}" "\\symfrak{N}" "\\symfrak{O}" "\\symfrak{P}" 
  "\\symfrak{Q}" "\\symfrak{R}" "\\symfrak{S}" "\\symfrak{T}" "\\symfrak{U}" 
  "\\symfrak{V}" "\\symfrak{W}" "\\symfrak{X}" "\\symfrak{Y}" "\\symfrak{Z}" 
  "\\symscr{A}" "\\symscr{B}" "\\symscr{C}" "\\symscr{D}" "\\symscr{E}" 
  "\\symscr{F}" "\\symscr{G}" "\\symscr{H}" "\\symscr{I}" "\\symscr{J}" 
  "\\symscr{K}" "\\symscr{L}" "\\symscr{M}" "\\symscr{N}" "\\symscr{O}" 
  "\\symscr{P}" "\\symscr{Q}" "\\symscr{R}" "\\symscr{S}" "\\symscr{T}" 
  "\\symscr{U}" "\\symscr{V}" "\\symscr{W}" "\\symscr{X}" "\\symscr{Y}" 
  "\\symscr{Z}" "\\symcal{A}" "\\symcal{B}" "\\symcal{C}" "\\symcal{D}" 
  "\\symcal{E}" "\\symcal{F}" "\\symcal{G}" "\\symcal{H}" "\\symcal{I}" 
  "\\symcal{J}" "\\symcal{K}" "\\symcal{L}" "\\symcal{M}" "\\symcal{N}" 
  "\\symcal{O}" "\\symcal{P}" "\\symcal{Q}" "\\symcal{R}" "\\symcal{S}" 
  "\\symcal{T}" "\\symcal{U}" "\\symcal{V}" "\\symcal{W}" "\\symcal{X}" 
  "\\symcal{Y}" "\\symcal{Z}")
 (#set-pairs! @text.math conceal
  "\\mathbb{A}" "𝔸"
  "\\mathbb{B}" "𝔹"
  "\\mathbb{C}" "ℂ"
  "\\mathbb{D}" "𝔻"
  "\\mathbb{E}" "𝔼"
  "\\mathbb{F}" "𝔽"
  "\\mathbb{G}" "𝔾"
  "\\mathbb{H}" "ℍ"
  "\\mathbb{I}" "𝕀"
  "\\mathbb{J}" "𝕁"
  "\\mathbb{K}" "𝕂"
  "\\mathbb{L}" "𝕃"
  "\\mathbb{M}" "𝕄"
  "\\mathbb{N}" "ℕ"
  "\\mathbb{O}" "𝕆"
  "\\mathbb{P}" "ℙ"
  "\\mathbb{Q}" "ℚ"
  "\\mathbb{R}" "ℝ"
  "\\mathbb{S}" "𝕊"
  "\\mathbb{T}" "𝕋"
  "\\mathbb{U}" "𝕌"
  "\\mathbb{V}" "𝕍"
  "\\mathbb{W}" "𝕎"
  "\\mathbb{X}" "𝕏"
  "\\mathbb{Y}" "𝕐"
  "\\mathbb{Z}" "ℤ"
  "\\mathsf{a}" "𝖺"
  "\\mathsf{b}" "𝖻"
  "\\mathsf{c}" "𝖼"
  "\\mathsf{d}" "𝖽"
  "\\mathsf{e}" "𝖾"
  "\\mathsf{f}" "𝖿"
  "\\mathsf{g}" "𝗀"
  "\\mathsf{h}" "𝗁"
  "\\mathsf{i}" "𝗂"
  "\\mathsf{j}" "𝗃"
  "\\mathsf{k}" "𝗄"
  "\\mathsf{l}" "𝗅"
  "\\mathsf{m}" "𝗆"
  "\\mathsf{n}" "𝗇"
  "\\mathsf{o}" "𝗈"
  "\\mathsf{p}" "𝗉"
  "\\mathsf{q}" "𝗊"
  "\\mathsf{r}" "𝗋"
  "\\mathsf{s}" "𝗌"
  "\\mathsf{t}" "𝗍"
  "\\mathsf{u}" "𝗎"
  "\\mathsf{v}" "𝗏"
  "\\mathsf{w}" "𝗐"
  "\\mathsf{x}" "𝗑"
  "\\mathsf{y}" "𝗒"
  "\\mathsf{z}" "𝗓"
  "\\mathsf{A}" "𝖠"
  "\\mathsf{B}" "𝖡"
  "\\mathsf{C}" "𝖢"
  "\\mathsf{D}" "𝖣"
  "\\mathsf{E}" "𝖤"
  "\\mathsf{F}" "𝖥"
  "\\mathsf{G}" "𝖦"
  "\\mathsf{H}" "𝖧"
  "\\mathsf{I}" "𝖨"
  "\\mathsf{J}" "𝖩"
  "\\mathsf{K}" "𝖪"
  "\\mathsf{L}" "𝖫"
  "\\mathsf{M}" "𝖬"
  "\\mathsf{N}" "𝖭"
  "\\mathsf{O}" "𝖮"
  "\\mathsf{P}" "𝖯"
  "\\mathsf{Q}" "𝖰"
  "\\mathsf{R}" "𝖱"
  "\\mathsf{S}" "𝖲"
  "\\mathsf{T}" "𝖳"
  "\\mathsf{U}" "𝖴"
  "\\mathsf{V}" "𝖵"
  "\\mathsf{W}" "𝖶"
  "\\mathsf{X}" "𝖷"
  "\\mathsf{Y}" "𝖸"
  "\\mathsf{Z}" "𝖹"
  "\\mathfrak{a}" "𝔞"
  "\\mathfrak{b}" "𝔟"
  "\\mathfrak{c}" "𝔠"
  "\\mathfrak{d}" "𝔡"
  "\\mathfrak{e}" "𝔢"
  "\\mathfrak{f}" "𝔣"
  "\\mathfrak{g}" "𝔤"
  "\\mathfrak{h}" "𝔥"
  "\\mathfrak{i}" "𝔦"
  "\\mathfrak{j}" "𝔧"
  "\\mathfrak{k}" "𝔨"
  "\\mathfrak{l}" "𝔩"
  "\\mathfrak{m}" "𝔪"
  "\\mathfrak{n}" "𝔫"
  "\\mathfrak{o}" "𝔬"
  "\\mathfrak{p}" "𝔭"
  "\\mathfrak{q}" "𝔮"
  "\\mathfrak{r}" "𝔯"
  "\\mathfrak{s}" "𝔰"
  "\\mathfrak{t}" "𝔱"
  "\\mathfrak{u}" "𝔲"
  "\\mathfrak{v}" "𝔳"
  "\\mathfrak{w}" "𝔴"
  "\\mathfrak{x}" "𝔵"
  "\\mathfrak{y}" "𝔶"
  "\\mathfrak{z}" "𝔷"
  "\\mathfrak{A}" "𝔄"
  "\\mathfrak{B}" "𝔅"
  "\\mathfrak{C}" "ℭ"
  "\\mathfrak{D}" "𝔇"
  "\\mathfrak{E}" "𝔈"
  "\\mathfrak{F}" "𝔉"
  "\\mathfrak{G}" "𝔊"
  "\\mathfrak{H}" "ℌ"
  "\\mathfrak{I}" "ℑ"
  "\\mathfrak{J}" "𝔍"
  "\\mathfrak{K}" "𝔎"
  "\\mathfrak{L}" "𝔏"
  "\\mathfrak{M}" "𝔐"
  "\\mathfrak{N}" "𝔑"
  "\\mathfrak{O}" "𝔒"
  "\\mathfrak{P}" "𝔓"
  "\\mathfrak{Q}" "𝔔"
  "\\mathfrak{R}" "ℜ"
  "\\mathfrak{S}" "𝔖"
  "\\mathfrak{T}" "𝔗"
  "\\mathfrak{U}" "𝔘"
  "\\mathfrak{V}" "𝔙"
  "\\mathfrak{W}" "𝔚"
  "\\mathfrak{X}" "𝔛"
  "\\mathfrak{Y}" "𝔜"
  "\\mathfrak{Z}" "ℨ"
  "\\mathscr{A}" "𝓐"
  "\\mathscr{B}" "𝓑"
  "\\mathscr{C}" "𝓒"
  "\\mathscr{D}" "𝓓"
  "\\mathscr{E}" "𝓔"
  "\\mathscr{F}" "𝓕"
  "\\mathscr{G}" "𝓖"
  "\\mathscr{H}" "𝓗"
  "\\mathscr{I}" "𝓘"
  "\\mathscr{J}" "𝓙"
  "\\mathscr{K}" "𝓚"
  "\\mathscr{L}" "𝓛"
  "\\mathscr{M}" "𝓜"
  "\\mathscr{N}" "𝓝"
  "\\mathscr{O}" "𝓞"
  "\\mathscr{P}" "𝓟"
  "\\mathscr{Q}" "𝓠"
  "\\mathscr{R}" "𝓡"
  "\\mathscr{S}" "𝓢"
  "\\mathscr{T}" "𝓣"
  "\\mathscr{U}" "𝓤"
  "\\mathscr{V}" "𝓥"
  "\\mathscr{W}" "𝓦"
  "\\mathscr{X}" "𝓧"
  "\\mathscr{Y}" "𝓨"
  "\\mathscr{Z}" "𝓩"
  "\\mathcal{A}" "𝓐"
  "\\mathcal{B}" "𝓑"
  "\\mathcal{C}" "𝓒"
  "\\mathcal{D}" "𝓓"
  "\\mathcal{E}" "𝓔"
  "\\mathcal{F}" "𝓕"
  "\\mathcal{G}" "𝓖"
  "\\mathcal{H}" "𝓗"
  "\\mathcal{I}" "𝓘"
  "\\mathcal{J}" "𝓙"
  "\\mathcal{K}" "𝓚"
  "\\mathcal{L}" "𝓛"
  "\\mathcal{M}" "𝓜"
  "\\mathcal{N}" "𝓝"
  "\\mathcal{O}" "𝓞"
  "\\mathcal{P}" "𝓟"
  "\\mathcal{Q}" "𝓠"
  "\\mathcal{R}" "𝓡"
  "\\mathcal{S}" "𝓢"
  "\\mathcal{T}" "𝓣"
  "\\mathcal{U}" "𝓤"
  "\\mathcal{V}" "𝓥"
  "\\mathcal{W}" "𝓦"
  "\\mathcal{X}" "𝓧"
  "\\mathcal{Y}" "𝓨"
  "\\mathcal{Z}" "𝓩"
  "\\symbb{A}" "𝔸"
  "\\symbb{B}" "𝔹"
  "\\symbb{C}" "ℂ"
  "\\symbb{D}" "𝔻"
  "\\symbb{E}" "𝔼"
  "\\symbb{F}" "𝔽"
  "\\symbb{G}" "𝔾"
  "\\symbb{H}" "ℍ"
  "\\symbb{I}" "𝕀"
  "\\symbb{J}" "𝕁"
  "\\symbb{K}" "𝕂"
  "\\symbb{L}" "𝕃"
  "\\symbb{M}" "𝕄"
  "\\symbb{N}" "ℕ"
  "\\symbb{O}" "𝕆"
  "\\symbb{P}" "ℙ"
  "\\symbb{Q}" "ℚ"
  "\\symbb{R}" "ℝ"
  "\\symbb{S}" "𝕊"
  "\\symbb{T}" "𝕋"
  "\\symbb{U}" "𝕌"
  "\\symbb{V}" "𝕍"
  "\\symbb{W}" "𝕎"
  "\\symbb{X}" "𝕏"
  "\\symbb{Y}" "𝕐"
  "\\symbb{Z}" "ℤ"
  "\\symsf{a}" "𝖺"
  "\\symsf{b}" "𝖻"
  "\\symsf{c}" "𝖼"
  "\\symsf{d}" "𝖽"
  "\\symsf{e}" "𝖾"
  "\\symsf{f}" "𝖿"
  "\\symsf{g}" "𝗀"
  "\\symsf{h}" "𝗁"
  "\\symsf{i}" "𝗂"
  "\\symsf{j}" "𝗃"
  "\\symsf{k}" "𝗄"
  "\\symsf{l}" "𝗅"
  "\\symsf{m}" "𝗆"
  "\\symsf{n}" "𝗇"
  "\\symsf{o}" "𝗈"
  "\\symsf{p}" "𝗉"
  "\\symsf{q}" "𝗊"
  "\\symsf{r}" "𝗋"
  "\\symsf{s}" "𝗌"
  "\\symsf{t}" "𝗍"
  "\\symsf{u}" "𝗎"
  "\\symsf{v}" "𝗏"
  "\\symsf{w}" "𝗐"
  "\\symsf{x}" "𝗑"
  "\\symsf{y}" "𝗒"
  "\\symsf{z}" "𝗓"
  "\\symsf{A}" "𝖠"
  "\\symsf{B}" "𝖡"
  "\\symsf{C}" "𝖢"
  "\\symsf{D}" "𝖣"
  "\\symsf{E}" "𝖤"
  "\\symsf{F}" "𝖥"
  "\\symsf{G}" "𝖦"
  "\\symsf{H}" "𝖧"
  "\\symsf{I}" "𝖨"
  "\\symsf{J}" "𝖩"
  "\\symsf{K}" "𝖪"
  "\\symsf{L}" "𝖫"
  "\\symsf{M}" "𝖬"
  "\\symsf{N}" "𝖭"
  "\\symsf{O}" "𝖮"
  "\\symsf{P}" "𝖯"
  "\\symsf{Q}" "𝖰"
  "\\symsf{R}" "𝖱"
  "\\symsf{S}" "𝖲"
  "\\symsf{T}" "𝖳"
  "\\symsf{U}" "𝖴"
  "\\symsf{V}" "𝖵"
  "\\symsf{W}" "𝖶"
  "\\symsf{X}" "𝖷"
  "\\symsf{Y}" "𝖸"
  "\\symsf{Z}" "𝖹"
  "\\symfrak{a}" "𝔞"
  "\\symfrak{b}" "𝔟"
  "\\symfrak{c}" "𝔠"
  "\\symfrak{d}" "𝔡"
  "\\symfrak{e}" "𝔢"
  "\\symfrak{f}" "𝔣"
  "\\symfrak{g}" "𝔤"
  "\\symfrak{h}" "𝔥"
  "\\symfrak{i}" "𝔦"
  "\\symfrak{j}" "𝔧"
  "\\symfrak{k}" "𝔨"
  "\\symfrak{l}" "𝔩"
  "\\symfrak{m}" "𝔪"
  "\\symfrak{n}" "𝔫"
  "\\symfrak{o}" "𝔬"
  "\\symfrak{p}" "𝔭"
  "\\symfrak{q}" "𝔮"
  "\\symfrak{r}" "𝔯"
  "\\symfrak{s}" "𝔰"
  "\\symfrak{t}" "𝔱"
  "\\symfrak{u}" "𝔲"
  "\\symfrak{v}" "𝔳"
  "\\symfrak{w}" "𝔴"
  "\\symfrak{x}" "𝔵"
  "\\symfrak{y}" "𝔶"
  "\\symfrak{z}" "𝔷"
  "\\symfrak{A}" "𝔄"
  "\\symfrak{B}" "𝔅"
  "\\symfrak{C}" "ℭ"
  "\\symfrak{D}" "𝔇"
  "\\symfrak{E}" "𝔈"
  "\\symfrak{F}" "𝔉"
  "\\symfrak{G}" "𝔊"
  "\\symfrak{H}" "ℌ"
  "\\symfrak{I}" "ℑ"
  "\\symfrak{J}" "𝔍"
  "\\symfrak{K}" "𝔎"
  "\\symfrak{L}" "𝔏"
  "\\symfrak{M}" "𝔐"
  "\\symfrak{N}" "𝔑"
  "\\symfrak{O}" "𝔒"
  "\\symfrak{P}" "𝔓"
  "\\symfrak{Q}" "𝔔"
  "\\symfrak{R}" "ℜ"
  "\\symfrak{S}" "𝔖"
  "\\symfrak{T}" "𝔗"
  "\\symfrak{U}" "𝔘"
  "\\symfrak{V}" "𝔙"
  "\\symfrak{W}" "𝔚"
  "\\symfrak{X}" "𝔛"
  "\\symfrak{Y}" "𝔜"
  "\\symfrak{Z}" "ℨ"
  "\\symscr{A}" "𝓐"
  "\\symscr{B}" "𝓑"
  "\\symscr{C}" "𝓒"
  "\\symscr{D}" "𝓓"
  "\\symscr{E}" "𝓔"
  "\\symscr{F}" "𝓕"
  "\\symscr{G}" "𝓖"
  "\\symscr{H}" "𝓗"
  "\\symscr{I}" "𝓘"
  "\\symscr{J}" "𝓙"
  "\\symscr{K}" "𝓚"
  "\\symscr{L}" "𝓛"
  "\\symscr{M}" "𝓜"
  "\\symscr{N}" "𝓝"
  "\\symscr{O}" "𝓞"
  "\\symscr{P}" "𝓟"
  "\\symscr{Q}" "𝓠"
  "\\symscr{R}" "𝓡"
  "\\symscr{S}" "𝓢"
  "\\symscr{T}" "𝓣"
  "\\symscr{U}" "𝓤"
  "\\symscr{V}" "𝓥"
  "\\symscr{W}" "𝓦"
  "\\symscr{X}" "𝓧"
  "\\symscr{Y}" "𝓨"
  "\\symscr{Z}" "𝓩"
  "\\symcal{A}" "𝓐"
  "\\symcal{B}" "𝓑"
  "\\symcal{C}" "𝓒"
  "\\symcal{D}" "𝓓"
  "\\symcal{E}" "𝓔"
  "\\symcal{F}" "𝓕"
  "\\symcal{G}" "𝓖"
  "\\symcal{H}" "𝓗"
  "\\symcal{I}" "𝓘"
  "\\symcal{J}" "𝓙"
  "\\symcal{K}" "𝓚"
  "\\symcal{L}" "𝓛"
  "\\symcal{M}" "𝓜"
  "\\symcal{N}" "𝓝"
  "\\symcal{O}" "𝓞"
  "\\symcal{P}" "𝓟"
  "\\symcal{Q}" "𝓠"
  "\\symcal{R}" "𝓡"
  "\\symcal{S}" "𝓢"
  "\\symcal{T}" "𝓣"
  "\\symcal{U}" "𝓤"
  "\\symcal{V}" "𝓥"
  "\\symcal{W}" "𝓦"
  "\\symcal{X}" "𝓧"
  "\\symcal{Y}" "𝓨"
  "\\symcal{Z}" "𝓩"))
